### ISSUE TITLE
ConnectionAdapter.Subscribe如何接收数据？

### ISSUE THREAD

**Issue by hessonsu** [emqx/emqx-extension-examples#13]
当我使用ConnectionAdapter.Subscribe 订阅testTopic 之后
我是如何接收testTopic 推送过来的的数据呢？
没有看到示例代码

**Comment by WangScaler** [comment]
订阅到的主题会回调onReceivedMessages，在这个方法里你可以ConnectionAdapter.send();
我之前写了java的demo,已提交PR,但是未合并，你可以去我的github查看demo。
