### ISSUE TITLE
how i can use it with emqx v5 ? 

### ISSUE THREAD

**Issue by MohsenHaydari** [emqx/emqx-extension-examples#27]
I tried to follow your python example, but I can't get data in the script, 

```

Started gRPC server on [::]:9000

````

![image](https://user-images.githubusercontent.com/56779182/215580260-a690b46a-5b00-42ba-9d00-efb414e31f91.png)

**Comment by richard-scott** [comment]
Change your URL to 127.0.0.1:9000

**Comment by MohsenHaydari** [comment]
> Change your URL to 127.0.0.1:9000

I try many ip but not working, I changed ```gRPC``` ip and port but not working 
![image](https://user-images.githubusercontent.com/56779182/215646089-6fe6f7d2-6d7d-47a3-9277-878e57c2456f.png)

**Comment by richard-scott** [comment]
You need to specify http such as:
http://127.0.0.1:9000

**Comment by MohsenHaydari** [comment]
> You need to specify http such as: http://127.0.0.1:9000

lol, thats working :) ty man
