### ISSUE TITLE
How can I prevent certain users from subscribing to some channels?[help]

### ISSUE THREAD

**Issue by MohsenHaydari** [emqx/emqx-extension-examples#28]
How can I prevent certain users from subscribing to some channels?
I check ```emqx``` documentation but I can't find anything.  I saw a method called OnClientCheckAcl, but it seems to have disappeared

**Comment by richard-scott** [comment]
I would either use [ACL's](https://www.emqx.io/docs/en/v5.0/access-control/authz/authz.html) or the OnClientAuthorize method.

**Comment by MohsenHaydari** [comment]
> Reference in n

I was working on that but it doesn't solve my problem, I can't use client ids or usernames for an authenticate users, I just want to do it through the topic name, what do you think I can do?

**Comment by richard-scott** [comment]
If you can't use Client ID or Usernames, then how can you identify the connection to block?

**Comment by MohsenHaydari** [comment]
> If you can't use Client ID or Usernames, then how can you identify the connection to block?

encryption algorithm, you think like find a signer

**Comment by richard-scott** [comment]
> encryption algorithm, you think like find a signer

I don't understand what this means, sorry.

**Comment by HJianBo** [comment]
> I saw a method called OnClientCheckAcl, but it seems to have disappeared

The `OnClientCheckAcl` is an old name in 4.4.x or 4.3.x. In 5.0 it renames to `OnClientAuthorize `
https://github.com/emqx/emqx/blob/e2884249242114a59878a4cc73b4e7864c8a0c43/apps/emqx_exhook/priv/protos/exhook.proto#L45

**Comment by MohsenHaydari** [comment]
> I would either use [ACL's](https://www.emqx.io/docs/en/v5.0/access-control/authz/authz.html) or the OnClientAuthorize method.
I had seen this before because I didn't receive anything in this method, so I thought it wasn't. I disabled the settings related to the  ACL file in the dashboard and now I see the accesses from this method. Is there a way to publish a message package with this package similar to the client? I know I can change the topic and redirect the message to another topic But I mean a different method
thanks guys

**Comment by MohsenHaydari** [comment]
> > I saw a method called OnClientCheckAcl, but it seems to have disappeared
> 
> The `OnClientCheckAcl` is an old name in 4.4.x or 4.3.x. In 5.0 it renames to `OnClientAuthorize ` https://github.com/emqx/emqx/blob/e2884249242114a59878a4cc73b4e7864c8a0c43/apps/emqx_exhook/priv/protos/exhook.proto#L45

I would either use [ACL's](https://www.emqx.io/docs/en/v5.0/access-control/authz/authz.html) or the OnClientAuthorize method.
I had seen this before because I didn't receive anything in this method, so I thought it wasn't. I disabled the settings related to the ACL file in the dashboard and now I see the accesses from this method. Is there a way to publish a message package with this package similar to the client? I know I can change the topic and redirect the message to another topic But I mean a different method
thanks guys
